package VIEW;

import DAO.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AutorVIEW extends javax.swing.JFrame {

    public void limparCampos (){
        txtNLivroVIEW.setText("");
        txtBestVIEW.setText("");
        txtAutorVIEW.setText("");
    }

    TratamentoDAO bd = new TratamentoDAO();
    /**
     * Creates new form frmConsultaVIEW
     */
    public AutorVIEW() {
        initComponents();
        readDatabase();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void readDatabase() {
        Connection conn;
        PreparedStatement pstm;
        conn = new ConexaoDAO().ConectaBD();
        String sql = "SELECT * FROM tabelaAutores";
        try {
            pstm = conn.prepareStatement(sql);
            ResultSet executarQuery = pstm.executeQuery();
            DefaultTableModel autorViewTable = (DefaultTableModel) tabelaAutorVIEW.getModel();
            autorViewTable.setNumRows(0);
            while (executarQuery.next()) {
                autorViewTable.addRow(new Object[]{
                    executarQuery.getString("idA"),
                    executarQuery.getString("autorA"),
                    executarQuery.getString("bestA"),
                    executarQuery.getString("nlivroA"),});
            }

        } catch (SQLException sqlex) {
            JOptionPane.showMessageDialog(null, "AutorVIEW: " + sqlex);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAutorVIEW = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAutorVIEW = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCadastrarVIEW = new javax.swing.JButton();
        btnLimparVIEW = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAlterarVIEW = new javax.swing.JButton();
        btnExcluirVIEW = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnSairVIEW2 = new javax.swing.JButton();
        txtBestVIEW = new javax.swing.JTextField();
        txtNLivroVIEW = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LIVRARIA RAI MUNDO");
        jLabel3.setPreferredSize(new java.awt.Dimension(900, 26));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("AUTORES");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("preencha apenas o que deseja consultar.");

        tabelaAutorVIEW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "AUTOR", "BESTSELLERS", "Nº LIVROS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAutorVIEW);
        if (tabelaAutorVIEW.getColumnModel().getColumnCount() > 0) {
            tabelaAutorVIEW.getColumnModel().getColumn(0).setMinWidth(45);
            tabelaAutorVIEW.getColumnModel().getColumn(0).setMaxWidth(45);
            tabelaAutorVIEW.getColumnModel().getColumn(3).setMinWidth(100);
            tabelaAutorVIEW.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jLabel2.setText("Autor:");

        jLabel6.setText("Bestsellers: ");

        txtAutorVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorVIEWActionPerformed(evt);
            }
        });

        jLabel7.setText("Nº Livros:");

        btnCadastrarVIEW.setText("CADASTRAR");
        btnCadastrarVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVIEWActionPerformed(evt);
            }
        });

        btnLimparVIEW.setText("LIMPAR");
        btnLimparVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparVIEWActionPerformed(evt);
            }
        });

        btnAlterarVIEW.setText("ALTERAR");
        btnAlterarVIEW.setEnabled(false);
        btnAlterarVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVIEWActionPerformed(evt);
            }
        });

        btnExcluirVIEW.setText("EXCLUIR");
        btnExcluirVIEW.setEnabled(false);
        btnExcluirVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirVIEWActionPerformed(evt);
            }
        });

        btnAlterar.setText("SALVAR");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnSairVIEW2.setBackground(new java.awt.Color(105, 105, 105));
        btnSairVIEW2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSairVIEW2.setForeground(new java.awt.Color(255, 255, 255));
        btnSairVIEW2.setText("v o l t a");
        btnSairVIEW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairVIEW2ActionPerformed(evt);
            }
        });

        txtBestVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBestVIEWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSairVIEW2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAutorVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnCadastrarVIEW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAlterarVIEW)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBestVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAlterar)
                                .addGap(127, 127, 127)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExcluirVIEW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimparVIEW))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNLivroVIEW)))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtAutorVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtBestVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNLivroVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarVIEW)
                    .addComponent(btnLimparVIEW)
                    .addComponent(btnAlterarVIEW)
                    .addComponent(btnExcluirVIEW)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairVIEW2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVIEWActionPerformed
           if (!txtAutorVIEW.getText().trim().isEmpty() && !txtBestVIEW.getText().trim().isEmpty() && !txtNLivroVIEW.getText().trim().isEmpty()) {
            Integer quantidadeDeLivros = Integer.valueOf(txtNLivroVIEW.getText().toString());
            bd.InsertAutorBd(txtAutorVIEW.getText().toString(), txtBestVIEW.getText().toString(), quantidadeDeLivros);

            readDatabase();
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos!");

        }

    }//GEN-LAST:event_btnCadastrarVIEWActionPerformed

    private void btnAlterarVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVIEWActionPerformed

    }//GEN-LAST:event_btnAlterarVIEWActionPerformed

    private void btnExcluirVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirVIEWActionPerformed

    }//GEN-LAST:event_btnExcluirVIEWActionPerformed

    private void btnLimparVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparVIEWActionPerformed
       limparCampos();
    }//GEN-LAST:event_btnLimparVIEWActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSairVIEW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairVIEW2ActionPerformed
        this.dispose();
        DashBoardVIEW tela = new DashBoardVIEW();
        tela.setVisible(true);
    }//GEN-LAST:event_btnSairVIEW2ActionPerformed

    private void txtAutorVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorVIEWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorVIEWActionPerformed

    private void txtBestVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBestVIEWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBestVIEWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutorVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarVIEW;
    private javax.swing.JButton btnCadastrarVIEW;
    private javax.swing.JButton btnExcluirVIEW;
    private javax.swing.JButton btnLimparVIEW;
    private javax.swing.JButton btnSairVIEW2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaAutorVIEW;
    private javax.swing.JTextField txtAutorVIEW;
    private javax.swing.JTextField txtBestVIEW;
    private javax.swing.JTextField txtNLivroVIEW;
    // End of variables declaration//GEN-END:variables

}
