package VIEW;

import DAO.ConexaoDAO;
import DAO.TratamentoDAO;
import VIEW.DashBoardVIEW;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LivroVIEW extends javax.swing.JFrame {

    TratamentoDAO Cadastrar = new TratamentoDAO();

    public void limparCampos (){
         txtLivroVIEW.setText("");
        txtQuantidadeVIEW.setText("");
        txtAutorVIEW.setText("");
        txtSecaoVIEW.setText("");
    }
    /**
     * Creates new form frmConsultaVIEW
     */
    public LivroVIEW() {
        initComponents();
        readDatabase();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void readDatabase() {
        Connection conn;
        PreparedStatement pstm;
        conn = new ConexaoDAO().ConectaBD();
        String sql = "SELECT * FROM tabelaLivros";
        try {
            pstm = conn.prepareStatement(sql);
            ResultSet executarQuery = pstm.executeQuery();
            DefaultTableModel livroViewTable = (DefaultTableModel) tabelaLivroVIEW.getModel();
            livroViewTable.setNumRows(0);
            while (executarQuery.next()) {
                livroViewTable.addRow(new Object[]{
                    executarQuery.getString("idL"),
                    executarQuery.getString("nomeL"),
                    executarQuery.getString("autorL"),
                    executarQuery.getString("secaoL"),
                    executarQuery.getString("quantidadeL"),});
            }

        } catch (SQLException sqlex) {
            JOptionPane.showMessageDialog(null, "LivroVIEW: " + sqlex);
        }
    }
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivroVIEW = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtQuantidadeVIEW = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLivroVIEW = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAutorVIEW = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSecaoVIEW = new javax.swing.JTextField();
        btnCadastrarVIEW = new javax.swing.JButton();
        btnLimparVIEW = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAlterarVIEW = new javax.swing.JButton();
        btnExcluirVIEW = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnSairVIEW2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LIVRARIA RAI MUNDO");
        jLabel3.setPreferredSize(new java.awt.Dimension(900, 26));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LIVROS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("preencha apenas o que deseja consultar.");

        tabelaLivroVIEW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "LIVRO", "AUTOR", "SECÃO", "QTD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaLivroVIEW);
        if (tabelaLivroVIEW.getColumnModel().getColumnCount() > 0) {
            tabelaLivroVIEW.getColumnModel().getColumn(0).setMinWidth(45);
            tabelaLivroVIEW.getColumnModel().getColumn(0).setMaxWidth(45);
            tabelaLivroVIEW.getColumnModel().getColumn(4).setMinWidth(60);
            tabelaLivroVIEW.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        jLabel1.setText("Quantidade: ");

        txtQuantidadeVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeVIEWActionPerformed(evt);
            }
        });

        jLabel2.setText("Livro: ");

        jLabel6.setText("Autor:");

        jLabel7.setText("Secão:");

        btnCadastrarVIEW.setText("CADASTRAR");
        btnCadastrarVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVIEWActionPerformed(evt);
            }
        });

        btnLimparVIEW.setText("LIMPAR");
        btnLimparVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparVIEWActionPerformed(evt);
            }
        });

        btnAlterarVIEW.setText("ALTERAR");
        btnAlterarVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarVIEWActionPerformed(evt);
            }
        });

        btnExcluirVIEW.setText("EXCLUIR");
        btnExcluirVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirVIEWActionPerformed(evt);
            }
        });

        btnAlterar.setText("SALVAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnSairVIEW2.setBackground(new java.awt.Color(105, 105, 105));
        btnSairVIEW2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSairVIEW2.setForeground(new java.awt.Color(255, 255, 255));
        btnSairVIEW2.setText("v o l t a");
        btnSairVIEW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairVIEW2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQuantidadeVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCadastrarVIEW))
                                .addGap(66, 66, 66)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAlterarVIEW)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAlterar))
                                    .addComponent(txtLivroVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluirVIEW)
                                    .addComponent(txtAutorVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimparVIEW))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSecaoVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSairVIEW2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuantidadeVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLivroVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtAutorVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSecaoVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarVIEW)
                    .addComponent(btnLimparVIEW)
                    .addComponent(btnAlterarVIEW)
                    .addComponent(btnExcluirVIEW)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairVIEW2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantidadeVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeVIEWActionPerformed

    }//GEN-LAST:event_txtQuantidadeVIEWActionPerformed

    private void btnCadastrarVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVIEWActionPerformed

        if (!txtLivroVIEW.getText().trim().isEmpty() && !txtAutorVIEW.getText().trim().isEmpty() && !txtSecaoVIEW.getText().trim().isEmpty() && !txtQuantidadeVIEW.getText().trim().isEmpty()) {
            Integer quantidade = Integer.valueOf(txtQuantidadeVIEW.getText().toString());
            Cadastrar.InsertLivroBd(txtLivroVIEW.getText().toString(), txtAutorVIEW.getText().toString(), txtSecaoVIEW.getText().toString(), quantidade);

            readDatabase();
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos!");

        }

    }//GEN-LAST:event_btnCadastrarVIEWActionPerformed

    private void btnAlterarVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarVIEWActionPerformed

        if (tabelaLivroVIEW.getSelectedRow() != -1) {
            txtQuantidadeVIEW.setText((String) tabelaLivroVIEW.getValueAt(tabelaLivroVIEW.getSelectedRow(), 4));
            txtSecaoVIEW.setText((String) tabelaLivroVIEW.getValueAt(tabelaLivroVIEW.getSelectedRow(), 3));
            txtAutorVIEW.setText((String) tabelaLivroVIEW.getValueAt(tabelaLivroVIEW.getSelectedRow(), 2));
            txtLivroVIEW.setText((String) tabelaLivroVIEW.getValueAt(tabelaLivroVIEW.getSelectedRow(), 1));
        
            
            
        }

    }//GEN-LAST:event_btnAlterarVIEWActionPerformed

    private void btnExcluirVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirVIEWActionPerformed
        if (tabelaLivroVIEW.getSelectedRow() != -1) {

            Cadastrar.DeleteLivro(Integer.valueOf(tabelaLivroVIEW.getValueAt(tabelaLivroVIEW.getSelectedRow(), 0).toString()));
            readDatabase();
 
        } else {
            JOptionPane.showMessageDialog(null, "Escolha um livro para excluir!");

        }
    }//GEN-LAST:event_btnExcluirVIEWActionPerformed

    private void btnLimparVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparVIEWActionPerformed
       limparCampos();
    }//GEN-LAST:event_btnLimparVIEWActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
         if (!txtLivroVIEW.getText().trim().isEmpty() && !txtAutorVIEW.getText().trim().isEmpty() && !txtSecaoVIEW.getText().trim().isEmpty() && !txtQuantidadeVIEW.getText().trim().isEmpty()) {
            Integer quantidade = Integer.valueOf(txtQuantidadeVIEW.getText().toString());
            Cadastrar.UpdateLivroBd(txtLivroVIEW.getText().toString(), txtAutorVIEW.getText().toString(), txtSecaoVIEW.getText().toString(), quantidade ,Integer.valueOf(tabelaLivroVIEW.getValueAt(tabelaLivroVIEW.getSelectedRow(), 0).toString()));

            readDatabase();
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos!");

        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSairVIEW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairVIEW2ActionPerformed
        this.dispose();
        DashBoardVIEW tela = new DashBoardVIEW();
        tela.setVisible(true);
    }//GEN-LAST:event_btnSairVIEW2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivroVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivroVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarVIEW;
    private javax.swing.JButton btnCadastrarVIEW;
    private javax.swing.JButton btnExcluirVIEW;
    private javax.swing.JButton btnLimparVIEW;
    private javax.swing.JButton btnSairVIEW2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaLivroVIEW;
    private javax.swing.JTextField txtAutorVIEW;
    private javax.swing.JTextField txtLivroVIEW;
    private javax.swing.JTextField txtQuantidadeVIEW;
    private javax.swing.JTextField txtSecaoVIEW;
    // End of variables declaration//GEN-END:variables

}
